---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: silverblue-secureblue-custom-template
# description will be included in the image's metadata
description: Template for personal OS image based on Secureblue

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/secureblue/silverblue-main-hardened
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
# see bluebuild docs for examples
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
